services:
  txt2holo:
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - STABILITY_API_KEY=<API_KEY>
      - OPENAI_API_KEY=<API_KEY>
      - IMAGE_BACKEND=stability